require 'core_ext/io/open_conditional'
require 'core_ext/object/command_line_arguments'
require 'core_ext/object/exception_ignore'
require 'core_ext/object/instance_variables'
require 'core_ext/string/unaccent'
